//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSImageHotspotPlugin\src\main\java\com\ashera\imagehotspot\HotspotEventCommand.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_HotspotEventCommand")
#ifdef RESTRICT_HotspotEventCommand
#define INCLUDE_ALL_HotspotEventCommand 0
#else
#define INCLUDE_ALL_HotspotEventCommand 1
#endif
#undef RESTRICT_HotspotEventCommand

#if !defined (ASHotspotEventCommand_) && (INCLUDE_ALL_HotspotEventCommand || defined(INCLUDE_ASHotspotEventCommand))
#define ASHotspotEventCommand_

#define RESTRICT_EventCommand 1
#define INCLUDE_ASEventCommand 1
#include "EventCommand.h"

@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASHotspotEventCommand : NSObject < ASEventCommand >

#pragma mark Public

- (instancetype)init;

- (id)executeCommandWithASIWidget:(id<ASIWidget>)widget
                  withJavaUtilMap:(id<JavaUtilMap>)eventObject
                withNSObjectArray:(IOSObjectArray *)params;

@end

J2OBJC_EMPTY_STATIC_INIT(ASHotspotEventCommand)

FOUNDATION_EXPORT void ASHotspotEventCommand_init(ASHotspotEventCommand *self);

FOUNDATION_EXPORT ASHotspotEventCommand *new_ASHotspotEventCommand_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASHotspotEventCommand *create_ASHotspotEventCommand_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASHotspotEventCommand)

@compatibility_alias ComAsheraImagehotspotHotspotEventCommand ASHotspotEventCommand;


#endif

#pragma pop_macro("INCLUDE_ALL_HotspotEventCommand")
