//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSImageHotspotPlugin\src\main\java\com\ashera\imagehotspot\HotspotEventCommand.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "EventBus.h"
#include "EventExpressionParser.h"
#include "HotspotEventCommand.h"
#include "IFragment.h"
#include "IOSObjectArray.h"
#include "IWidget.h"
#include "J2ObjC_source.h"
#include "java/lang/Integer.h"
#include "java/util/Map.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation ASHotspotEventCommand

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASHotspotEventCommand_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id)executeCommandWithASIWidget:(id<ASIWidget>)widget
                  withJavaUtilMap:(id<JavaUtilMap>)eventObject
                withNSObjectArray:(IOSObjectArray *)params {
  NSString *event = (NSString *) cast_chk([((id<JavaUtilMap>) nil_chk(eventObject)) getWithId:ASEventExpressionParser_KEY_SCRIPT_NAME], [NSString class]);
  switch (JreIndexOfStr(event, (id[]){ @"onTouch" }, 1)) {
    case 0:
    {
      [((ASEventBus *) nil_chk([((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(widget)) getFragment])) getEventBus])) notifyObserversWithNSString:JreStrcat("$$", [widget getId], @"OnTouch") withId:eventObject];
      break;
    }
  }
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x81, 0, 1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(executeCommandWithASIWidget:withJavaUtilMap:withNSObjectArray:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "executeCommand", "LASIWidget;LJavaUtilMap;[LNSObject;", "(Lcom/ashera/widget/IWidget;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;[Ljava/lang/Object;)Ljava/lang/Object;" };
  static const J2ObjcClassInfo _ASHotspotEventCommand = { "HotspotEventCommand", "com.ashera.imagehotspot", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASHotspotEventCommand;
}

@end

void ASHotspotEventCommand_init(ASHotspotEventCommand *self) {
  NSObject_init(self);
}

ASHotspotEventCommand *new_ASHotspotEventCommand_init() {
  J2OBJC_NEW_IMPL(ASHotspotEventCommand, init)
}

ASHotspotEventCommand *create_ASHotspotEventCommand_init() {
  J2OBJC_CREATE_IMPL(ASHotspotEventCommand, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASHotspotEventCommand)

J2OBJC_NAME_MAPPING(ASHotspotEventCommand, "com.ashera.imagehotspot", "AS")
