//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSImageHotspotPlugin\src\main\java\com\ashera\imagehotspot\ImageHotspotViewImpl.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "Drawable.h"
#include "EventBus.h"
#include "EventBusHandler.h"
#include "EventCommand.h"
#include "EventCommandFactory.h"
#include "EventExpressionParser.h"
#include "Handler.h"
#include "IActivity.h"
#include "IAttributable.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IListener.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IWidget.h"
#include "ImageHotspotViewImpl.h"
#include "ImageView.h"
#include "J2ObjC_source.h"
#include "ModelExpressionParser.h"
#include "MotionEvent.h"
#include "PluginInvoker.h"
#include "PointF.h"
#include "RectM.h"
#include "View.h"
#include "ViewImpl.h"
#include "ViewOverlay.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/Math.h"
#include "java/lang/Runnable.h"
#include "java/util/ArrayList.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "java/util/WeakHashMap.h"
#include "java/util/function/Function.h"
#include "java/util/function/Predicate.h"
#include "java/util/stream/Stream.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"


@class ASImageHotspotViewImpl_Hotspot;
@class NSString;


#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


#pragma clang diagnostic ignored "-Wprotocol"

@interface ASImageHotspotViewImpl () {
 @public
  id<ASIWidget> w_;
  id<JavaUtilMap> instances_;
  id<JavaUtilList> hotspots_;
  NSString *hotspotOverlayDrawable_;
  id<JavaUtilMap> hotspotOverlayDrawablesByType_;
  bool hotspotDetectOnlyOnce_;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)widget;

- (void)setHotSpotsWithASIWidget:(id<ASIWidget>)w
                          withId:(id)value;

- (ASImageHotspotViewImpl_Hotspot *)findHotspotWithADImageView:(ADImageView *)imageView
                                                     withFloat:(float)viewX
                                                     withFloat:(float)viewY;

- (void)setOnHotspotClickWithASIWidget:(id<ASIWidget>)w
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setHotspotOverlayDrawableWithASIWidget:(id<ASIWidget>)w2
                                  withNSString:(NSString *)strValue
                                        withId:(id)objValue
                                    withADView:(ADView *)view;

- (void)setHotspotOverlayDrawablesByTypeWithASIWidget:(id<ASIWidget>)w2
                                         withNSString:(NSString *)strValue
                                               withId:(id)objValue
                                           withADView:(ADView *)view;

- (void)setHotspotDetectOnlyOnceWithASIWidget:(id<ASIWidget>)w2
                                 withNSString:(NSString *)strValue
                                       withId:(id)objValue
                                   withADView:(ADView *)view;

- (void)showDebugHotspotsWithADImageView:(ADImageView *)imageView;

- (ADDrawable *)createDebugDrawableWithInt:(int32_t)left
                                   withInt:(int32_t)top
                                   withInt:(int32_t)right
                                   withInt:(int32_t)bottom;

- (ASImageHotspotViewImpl_ImageTransform *)fromImageViewWithADImageView:(ADImageView *)imageView;

- (void)requestLayoutWithADImageView:(ADImageView *)imageView;

- (void)setUseGcWithADDrawable:(ADDrawable *)markerCopy;

@end

J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl, w_, id<ASIWidget>)
J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl, instances_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl, hotspots_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl, hotspotOverlayDrawable_, NSString *)
J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl, hotspotOverlayDrawablesByType_, id<JavaUtilMap>)

__attribute__((unused)) static void ASImageHotspotViewImpl_initWithASIWidget_(ASImageHotspotViewImpl *self, id<ASIWidget> widget);

__attribute__((unused)) static ASImageHotspotViewImpl *new_ASImageHotspotViewImpl_initWithASIWidget_(id<ASIWidget> widget) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASImageHotspotViewImpl *create_ASImageHotspotViewImpl_initWithASIWidget_(id<ASIWidget> widget);

__attribute__((unused)) static void ASImageHotspotViewImpl_setHotSpotsWithASIWidget_withId_(ASImageHotspotViewImpl *self, id<ASIWidget> w, id value);

__attribute__((unused)) static ASImageHotspotViewImpl_Hotspot *ASImageHotspotViewImpl_findHotspotWithADImageView_withFloat_withFloat_(ASImageHotspotViewImpl *self, ADImageView *imageView, float viewX, float viewY);

__attribute__((unused)) static void ASImageHotspotViewImpl_setOnHotspotClickWithASIWidget_withNSString_withId_(ASImageHotspotViewImpl *self, id<ASIWidget> w, NSString *strValue, id objValue);

__attribute__((unused)) static void ASImageHotspotViewImpl_setHotspotOverlayDrawableWithASIWidget_withNSString_withId_withADView_(ASImageHotspotViewImpl *self, id<ASIWidget> w2, NSString *strValue, id objValue, ADView *view);

__attribute__((unused)) static void ASImageHotspotViewImpl_setHotspotOverlayDrawablesByTypeWithASIWidget_withNSString_withId_withADView_(ASImageHotspotViewImpl *self, id<ASIWidget> w2, NSString *strValue, id objValue, ADView *view);

__attribute__((unused)) static void ASImageHotspotViewImpl_setHotspotDetectOnlyOnceWithASIWidget_withNSString_withId_withADView_(ASImageHotspotViewImpl *self, id<ASIWidget> w2, NSString *strValue, id objValue, ADView *view);

__attribute__((unused)) static void ASImageHotspotViewImpl_showDebugHotspotsWithADImageView_(ASImageHotspotViewImpl *self, ADImageView *imageView);

__attribute__((unused)) static ADDrawable *ASImageHotspotViewImpl_createDebugDrawableWithInt_withInt_withInt_withInt_(ASImageHotspotViewImpl *self, int32_t left, int32_t top, int32_t right, int32_t bottom);

__attribute__((unused)) static ASImageHotspotViewImpl_ImageTransform *ASImageHotspotViewImpl_fromImageViewWithADImageView_(ASImageHotspotViewImpl *self, ADImageView *imageView);

__attribute__((unused)) static void ASImageHotspotViewImpl_requestLayoutWithADImageView_(ASImageHotspotViewImpl *self, ADImageView *imageView);

__attribute__((unused)) static void ASImageHotspotViewImpl_setUseGcWithADDrawable_(ASImageHotspotViewImpl *self, ADDrawable *markerCopy);

@interface ASImageHotspotViewImpl_Hotspot : NSObject {
 @public
  NSString *id__;
  NSString *type_;
  float percX_;
  bool found_;
  float percY_;
  float percWidth_;
  float percHeight_;
  float imageWidth_;
  float imageHeight_;
}

- (instancetype)initWithASImageHotspotViewImpl:(ASImageHotspotViewImpl *)outer$;

- (bool)containsWithFloat:(float)normalizedX
                withFloat:(float)normalizedY;

- (NSString *)getType;

@end

J2OBJC_EMPTY_STATIC_INIT(ASImageHotspotViewImpl_Hotspot)

J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl_Hotspot, id__, NSString *)
J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl_Hotspot, type_, NSString *)

__attribute__((unused)) static void ASImageHotspotViewImpl_Hotspot_initWithASImageHotspotViewImpl_(ASImageHotspotViewImpl_Hotspot *self, ASImageHotspotViewImpl *outer$);

__attribute__((unused)) static ASImageHotspotViewImpl_Hotspot *new_ASImageHotspotViewImpl_Hotspot_initWithASImageHotspotViewImpl_(ASImageHotspotViewImpl *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASImageHotspotViewImpl_Hotspot *create_ASImageHotspotViewImpl_Hotspot_initWithASImageHotspotViewImpl_(ASImageHotspotViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASImageHotspotViewImpl_Hotspot)


@interface ASImageHotspotViewImpl_1 : ASEventBusHandler {
 @public
  ASImageHotspotViewImpl *this$0_;
  id<ASIWidget> val$w_;
  id val$objValue_;
}

- (instancetype)initWithASImageHotspotViewImpl:(ASImageHotspotViewImpl *)outer$
                                 withASIWidget:(id<ASIWidget>)capture$0
                                        withId:(id)capture$1
                                  withNSString:(NSString *)type;

- (void)doPerformWithId:(id)payload;

- (id<JavaUtilMap>)getRemainingHotspotsByType;

- (void)addOverlayWithASIWidget:(id<ASIWidget>)w
withASImageHotspotViewImpl_Hotspot:(ASImageHotspotViewImpl_Hotspot *)hotspot;

@end

J2OBJC_EMPTY_STATIC_INIT(ASImageHotspotViewImpl_1)

__attribute__((unused)) static void ASImageHotspotViewImpl_1_initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_(ASImageHotspotViewImpl_1 *self, ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0, id capture$1, NSString *type);

__attribute__((unused)) static ASImageHotspotViewImpl_1 *new_ASImageHotspotViewImpl_1_initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_(ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0, id capture$1, NSString *type) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASImageHotspotViewImpl_1 *create_ASImageHotspotViewImpl_1_initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_(ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0, id capture$1, NSString *type);

__attribute__((unused)) static id<JavaUtilMap> ASImageHotspotViewImpl_1_getRemainingHotspotsByType(ASImageHotspotViewImpl_1 *self);

__attribute__((unused)) static void ASImageHotspotViewImpl_1_addOverlayWithASIWidget_withASImageHotspotViewImpl_Hotspot_(ASImageHotspotViewImpl_1 *self, id<ASIWidget> w, ASImageHotspotViewImpl_Hotspot *hotspot);


@interface ASImageHotspotViewImpl_1_$Lambda$1 : NSObject < JavaUtilFunctionPredicate >

- (bool)testWithId:(ASImageHotspotViewImpl_Hotspot *)f;

@end

J2OBJC_STATIC_INIT(ASImageHotspotViewImpl_1_$Lambda$1)

inline ASImageHotspotViewImpl_1_$Lambda$1 *ASImageHotspotViewImpl_1_$Lambda$1_get_instance(void);
static ASImageHotspotViewImpl_1_$Lambda$1 *ASImageHotspotViewImpl_1_$Lambda$1_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASImageHotspotViewImpl_1_$Lambda$1, instance, ASImageHotspotViewImpl_1_$Lambda$1 *)

__attribute__((unused)) static void ASImageHotspotViewImpl_1_$Lambda$1_init(ASImageHotspotViewImpl_1_$Lambda$1 *self);

__attribute__((unused)) static ASImageHotspotViewImpl_1_$Lambda$1 *new_ASImageHotspotViewImpl_1_$Lambda$1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASImageHotspotViewImpl_1_$Lambda$1 *create_ASImageHotspotViewImpl_1_$Lambda$1_init(void);


@interface ASImageHotspotViewImpl_ImageHotspotView : NSObject

@end

@interface ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener : NSObject

@end

@interface ASImageHotspotViewImpl_OnHotspotClickListener : NSObject < ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener, ASIListener > {
 @public
  id<ASIWidget> w_;
  ADView *view_;
  NSString *strValue_;
  NSString *action_;
}

- (NSString *)getAction;

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue;

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue
                     withNSString:(NSString *)action;

- (bool)onHotspotClickWithASImageHotspotViewImpl_Hotspot:(ASImageHotspotViewImpl_Hotspot *)hotspot
                                                 withInt:(int32_t)remainingHotSpots
                                         withJavaUtilMap:(id<JavaUtilMap>)remainingHotSpotsByType;

- (id<JavaUtilMap>)getOnHotspotClickEventObjWithASImageHotspotViewImpl_Hotspot:(ASImageHotspotViewImpl_Hotspot *)hotspot
                                                                       withInt:(int32_t)remainingHotSpots
                                                               withJavaUtilMap:(id<JavaUtilMap>)remainingHotSpotsByType;

@end

J2OBJC_EMPTY_STATIC_INIT(ASImageHotspotViewImpl_OnHotspotClickListener)

J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl_OnHotspotClickListener, w_, id<ASIWidget>)
J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl_OnHotspotClickListener, view_, ADView *)
J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl_OnHotspotClickListener, strValue_, NSString *)
J2OBJC_FIELD_SETTER(ASImageHotspotViewImpl_OnHotspotClickListener, action_, NSString *)

__attribute__((unused)) static void ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_(ASImageHotspotViewImpl_OnHotspotClickListener *self, id<ASIWidget> w, NSString *strValue);

__attribute__((unused)) static ASImageHotspotViewImpl_OnHotspotClickListener *new_ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASImageHotspotViewImpl_OnHotspotClickListener *create_ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue);

__attribute__((unused)) static void ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_withNSString_(ASImageHotspotViewImpl_OnHotspotClickListener *self, id<ASIWidget> w, NSString *strValue, NSString *action);

__attribute__((unused)) static ASImageHotspotViewImpl_OnHotspotClickListener *new_ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASImageHotspotViewImpl_OnHotspotClickListener *create_ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action);

J2OBJC_TYPE_LITERAL_HEADER(ASImageHotspotViewImpl_OnHotspotClickListener)


@interface ASImageHotspotViewImpl_$Lambda$1 : NSObject < JavaUtilFunctionFunction >

- (id)applyWithId:(id<ASIWidget>)w;

@end

J2OBJC_STATIC_INIT(ASImageHotspotViewImpl_$Lambda$1)

inline ASImageHotspotViewImpl_$Lambda$1 *ASImageHotspotViewImpl_$Lambda$1_get_instance(void);
static ASImageHotspotViewImpl_$Lambda$1 *ASImageHotspotViewImpl_$Lambda$1_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASImageHotspotViewImpl_$Lambda$1, instance, ASImageHotspotViewImpl_$Lambda$1 *)

__attribute__((unused)) static void ASImageHotspotViewImpl_$Lambda$1_init(ASImageHotspotViewImpl_$Lambda$1 *self);

__attribute__((unused)) static ASImageHotspotViewImpl_$Lambda$1 *new_ASImageHotspotViewImpl_$Lambda$1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASImageHotspotViewImpl_$Lambda$1 *create_ASImageHotspotViewImpl_$Lambda$1_init(void);


@interface ASImageHotspotViewImpl_$Lambda$2 : NSObject < JavaLangRunnable > {
 @public
  ASImageHotspotViewImpl *this$0_;
  id<ASIWidget> val$w_;
}

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ASImageHotspotViewImpl_$Lambda$2)

__attribute__((unused)) static void ASImageHotspotViewImpl_$Lambda$2_initWithASImageHotspotViewImpl_withASIWidget_(ASImageHotspotViewImpl_$Lambda$2 *self, ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0);

__attribute__((unused)) static ASImageHotspotViewImpl_$Lambda$2 *new_ASImageHotspotViewImpl_$Lambda$2_initWithASImageHotspotViewImpl_withASIWidget_(ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASImageHotspotViewImpl_$Lambda$2 *create_ASImageHotspotViewImpl_$Lambda$2_initWithASImageHotspotViewImpl_withASIWidget_(ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0);


NSString *ASImageHotspotViewImpl_LOCAL_NAME = @"ImageHotspotView";

@implementation ASImageHotspotViewImpl

- (instancetype)initWithASIWidget:(id<ASIWidget>)widget {
  ASImageHotspotViewImpl_initWithASIWidget_(self, widget);
  return self;
}

- (NSString *)getLocalName {
  return ASImageHotspotViewImpl_LOCAL_NAME;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASImageHotspotViewImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<ASIAttributable>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  return [((id<JavaUtilMap>) nil_chk(instances_)) computeIfAbsentWithId:widget withJavaUtilFunctionFunction:JreLoadStatic(ASImageHotspotViewImpl_$Lambda$1, instance)];
}

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"hotspots"])) withTypeWithNSString:@"array"])) withArrayTypeWithNSString:@"resourcestring"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"onhotspotClick"])) withTypeWithNSString:@"string"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"hotspotOverlayDrawable"])) withTypeWithNSString:@"string"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"hotspotOverlayDrawablesByType"])) withTypeWithNSString:@"string"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"hotspotDetectOnlyOnce"])) withTypeWithNSString:@"boolean"]);
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w_)) asWidget], [ADView class]);
  id nativeWidget = [((id<ASIWidget>) nil_chk(w_)) asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"hotspots", @"onhotspotClick", @"hotspotOverlayDrawable", @"hotspotOverlayDrawablesByType", @"hotspotDetectOnlyOnce" }, 5)) {
    case 0:
    {
      ASImageHotspotViewImpl_setHotSpotsWithASIWidget_withId_(self, w_, objValue);
    }
    break;
    case 1:
    {
      ASImageHotspotViewImpl_setOnHotspotClickWithASIWidget_withNSString_withId_(self, w_, strValue, objValue);
    }
    break;
    case 2:
    {
      ASImageHotspotViewImpl_setHotspotOverlayDrawableWithASIWidget_withNSString_withId_withADView_(self, w_, strValue, objValue, view);
    }
    break;
    case 3:
    {
      ASImageHotspotViewImpl_setHotspotOverlayDrawablesByTypeWithASIWidget_withNSString_withId_withADView_(self, w_, strValue, objValue, view);
    }
    break;
    case 4:
    {
      ASImageHotspotViewImpl_setHotspotDetectOnlyOnceWithASIWidget_withNSString_withId_withADView_(self, w_, strValue, objValue, view);
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w_)) asWidget], [ADView class]);
  id nativeWidget = [((id<ASIWidget>) nil_chk(w_)) asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){  }, 0)) {
  }
  return nil;
}

- (void)setHotSpotsWithASIWidget:(id<ASIWidget>)w
                          withId:(id)value {
  ASImageHotspotViewImpl_setHotSpotsWithASIWidget_withId_(self, w, value);
}

- (ASImageHotspotViewImpl_Hotspot *)findHotspotWithADImageView:(ADImageView *)imageView
                                                     withFloat:(float)viewX
                                                     withFloat:(float)viewY {
  return ASImageHotspotViewImpl_findHotspotWithADImageView_withFloat_withFloat_(self, imageView, viewX, viewY);
}

- (void)setOnHotspotClickWithASIWidget:(id<ASIWidget>)w
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ASImageHotspotViewImpl_setOnHotspotClickWithASIWidget_withNSString_withId_(self, w, strValue, objValue);
}

- (void)setHotspotOverlayDrawableWithASIWidget:(id<ASIWidget>)w2
                                  withNSString:(NSString *)strValue
                                        withId:(id)objValue
                                    withADView:(ADView *)view {
  ASImageHotspotViewImpl_setHotspotOverlayDrawableWithASIWidget_withNSString_withId_withADView_(self, w2, strValue, objValue, view);
}

- (void)setHotspotOverlayDrawablesByTypeWithASIWidget:(id<ASIWidget>)w2
                                         withNSString:(NSString *)strValue
                                               withId:(id)objValue
                                           withADView:(ADView *)view {
  ASImageHotspotViewImpl_setHotspotOverlayDrawablesByTypeWithASIWidget_withNSString_withId_withADView_(self, w2, strValue, objValue, view);
}

- (void)setHotspotDetectOnlyOnceWithASIWidget:(id<ASIWidget>)w2
                                 withNSString:(NSString *)strValue
                                       withId:(id)objValue
                                   withADView:(ADView *)view {
  ASImageHotspotViewImpl_setHotspotDetectOnlyOnceWithASIWidget_withNSString_withId_withADView_(self, w2, strValue, objValue, view);
}

+ (void)addEventInfoWithJavaUtilMap:(id<JavaUtilMap>)obj
 withASImageHotspotViewImpl_Hotspot:(ASImageHotspotViewImpl_Hotspot *)hotspot {
  ASImageHotspotViewImpl_addEventInfoWithJavaUtilMap_withASImageHotspotViewImpl_Hotspot_(obj, hotspot);
}

+ (void)addEventInfoWithJavaUtilMap:(id<JavaUtilMap>)obj
                    withJavaUtilMap:(id<JavaUtilMap>)remainingHotSpotsByType {
  ASImageHotspotViewImpl_addEventInfoWithJavaUtilMap_withJavaUtilMap_(obj, remainingHotSpotsByType);
}

- (void)showDebugHotspotsWithADImageView:(ADImageView *)imageView {
  ASImageHotspotViewImpl_showDebugHotspotsWithADImageView_(self, imageView);
}

- (ADDrawable *)createDebugDrawableWithInt:(int32_t)left
                                   withInt:(int32_t)top
                                   withInt:(int32_t)right
                                   withInt:(int32_t)bottom {
  return ASImageHotspotViewImpl_createDebugDrawableWithInt_withInt_withInt_withInt_(self, left, top, right, bottom);
}

- (ASImageHotspotViewImpl_ImageTransform *)fromImageViewWithADImageView:(ADImageView *)imageView {
  return ASImageHotspotViewImpl_fromImageViewWithADImageView_(self, imageView);
}

- (void)requestLayoutWithADImageView:(ADImageView *)imageView {
  ASImageHotspotViewImpl_requestLayoutWithADImageView_(self, imageView);
}

- (void)setUseGcWithADDrawable:(ADDrawable *)markerCopy {
  ASImageHotspotViewImpl_setUseGcWithADDrawable_(self, markerCopy);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASIAttributable;", 0x1, 1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 8, 9, -1, -1, -1, -1 },
    { NULL, "LASImageHotspotViewImpl_Hotspot;", 0x2, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 13, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 14, 15, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 16, 15, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 17, 15, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 18, 19, -1, 20, -1, -1 },
    { NULL, "V", 0x9, 18, 21, -1, 22, -1, -1 },
    { NULL, "V", 0x2, 23, 24, -1, -1, -1, -1 },
    { NULL, "LADDrawable;", 0x2, 25, 26, -1, -1, -1, -1 },
    { NULL, "LASImageHotspotViewImpl_ImageTransform;", 0x2, 27, 24, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 28, 24, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 29, 30, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASIWidget:);
  methods[1].selector = @selector(getLocalName);
  methods[2].selector = @selector(init);
  methods[3].selector = @selector(newInstanceWithASIWidget:);
  methods[4].selector = @selector(loadAttributesWithNSString:);
  methods[5].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[6].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[7].selector = @selector(setHotSpotsWithASIWidget:withId:);
  methods[8].selector = @selector(findHotspotWithADImageView:withFloat:withFloat:);
  methods[9].selector = @selector(setOnHotspotClickWithASIWidget:withNSString:withId:);
  methods[10].selector = @selector(setHotspotOverlayDrawableWithASIWidget:withNSString:withId:withADView:);
  methods[11].selector = @selector(setHotspotOverlayDrawablesByTypeWithASIWidget:withNSString:withId:withADView:);
  methods[12].selector = @selector(setHotspotDetectOnlyOnceWithASIWidget:withNSString:withId:withADView:);
  methods[13].selector = @selector(addEventInfoWithJavaUtilMap:withASImageHotspotViewImpl_Hotspot:);
  methods[14].selector = @selector(addEventInfoWithJavaUtilMap:withJavaUtilMap:);
  methods[15].selector = @selector(showDebugHotspotsWithADImageView:);
  methods[16].selector = @selector(createDebugDrawableWithInt:withInt:withInt:withInt:);
  methods[17].selector = @selector(fromImageViewWithADImageView:);
  methods[18].selector = @selector(requestLayoutWithADImageView:);
  methods[19].selector = @selector(setUseGcWithADDrawable:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 31, -1, -1 },
    { "w_", "LASIWidget;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "instances_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 32, -1 },
    { "hotspots_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 33, -1 },
    { "hotspotOverlayDrawable_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "hotspotOverlayDrawablesByType_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 34, -1 },
    { "hotspotDetectOnlyOnce_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASIWidget;", "newInstance", "loadAttributes", "LNSString;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "setHotSpots", "LASIWidget;LNSObject;", "findHotspot", "LADImageView;FF", "setOnHotspotClick", "LASIWidget;LNSString;LNSObject;", "setHotspotOverlayDrawable", "LASIWidget;LNSString;LNSObject;LADView;", "setHotspotOverlayDrawablesByType", "setHotspotDetectOnlyOnce", "addEventInfo", "LJavaUtilMap;LASImageHotspotViewImpl_Hotspot;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;Lcom/ashera/imagehotspot/ImageHotspotViewImpl$Hotspot;)V", "LJavaUtilMap;LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;Ljava/util/Map;)V", "showDebugHotspots", "LADImageView;", "createDebugDrawable", "IIII", "fromImageView", "requestLayout", "setUseGc", "LADDrawable;", &ASImageHotspotViewImpl_LOCAL_NAME, "Ljava/util/Map<Lcom/ashera/widget/IWidget;Lcom/ashera/widget/IAttributable;>;", "Ljava/util/List<Lcom/ashera/imagehotspot/ImageHotspotViewImpl$Hotspot;>;", "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;", "LASImageHotspotViewImpl_Hotspot;LASImageHotspotViewImpl_ImageTransform;LASImageHotspotViewImpl_ImageHotspotView;LASImageHotspotViewImpl_OnHotspotClickListener;" };
  static const J2ObjcClassInfo _ASImageHotspotViewImpl = { "ImageHotspotViewImpl", "com.ashera.imagehotspot", ptrTable, methods, fields, 7, 0x1, 20, 7, -1, 35, -1, -1, -1 };
  return &_ASImageHotspotViewImpl;
}

@end

void ASImageHotspotViewImpl_initWithASIWidget_(ASImageHotspotViewImpl *self, id<ASIWidget> widget) {
  NSObject_init(self);
  self->instances_ = new_JavaUtilWeakHashMap_init();
  self->w_ = widget;
}

ASImageHotspotViewImpl *new_ASImageHotspotViewImpl_initWithASIWidget_(id<ASIWidget> widget) {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl, initWithASIWidget_, widget)
}

ASImageHotspotViewImpl *create_ASImageHotspotViewImpl_initWithASIWidget_(id<ASIWidget> widget) {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl, initWithASIWidget_, widget)
}

void ASImageHotspotViewImpl_init(ASImageHotspotViewImpl *self) {
  NSObject_init(self);
  self->instances_ = new_JavaUtilWeakHashMap_init();
}

ASImageHotspotViewImpl *new_ASImageHotspotViewImpl_init() {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl, init)
}

ASImageHotspotViewImpl *create_ASImageHotspotViewImpl_init() {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl, init)
}

void ASImageHotspotViewImpl_setHotSpotsWithASIWidget_withId_(ASImageHotspotViewImpl *self, id<ASIWidget> w, id value) {
  self->hotspots_ = new_JavaUtilArrayList_init();
  id<JavaUtilList> hotspotDefs = (id<JavaUtilList>) cast_check(value, JavaUtilList_class_());
  for (id __strong hotspotDef in nil_chk(hotspotDefs)) {
    id<JavaUtilMap> params = ASModelExpressionParser_parseSimpleCssExpressionWithNSString_((NSString *) cast_chk(hotspotDef, [NSString class]));
    ASImageHotspotViewImpl_Hotspot *hotspot = new_ASImageHotspotViewImpl_Hotspot_initWithASImageHotspotViewImpl_(self);
    hotspot->id__ = (NSString *) cast_chk([((id<JavaUtilMap>) nil_chk(params)) getWithId:@"id"], [NSString class]);
    hotspot->type_ = (NSString *) cast_chk([params getWithId:@"type"], [NSString class]);
    hotspot->imageWidth_ = JavaLangFloat_parseFloatWithNSString_((NSString *) cast_chk([params getWithId:@"imageWidth"], [NSString class]));
    hotspot->imageHeight_ = JavaLangFloat_parseFloatWithNSString_((NSString *) cast_chk([params getWithId:@"imageHeight"], [NSString class]));
    hotspot->percX_ = JavaLangFloat_parseFloatWithNSString_((NSString *) cast_chk([params getWithId:@"percX"], [NSString class]));
    hotspot->percY_ = JavaLangFloat_parseFloatWithNSString_((NSString *) cast_chk([params getWithId:@"percY"], [NSString class]));
    hotspot->percWidth_ = JavaLangFloat_parseFloatWithNSString_((NSString *) cast_chk([params getWithId:@"percWidth"], [NSString class]));
    hotspot->percHeight_ = JavaLangFloat_parseFloatWithNSString_((NSString *) cast_chk([params getWithId:@"percHeight"], [NSString class]));
    [((id<JavaUtilList>) nil_chk(self->hotspots_)) addWithId:hotspot];
  }
  [new_ADHandler_init() postWithJavaLangRunnable:new_ASImageHotspotViewImpl_$Lambda$2_initWithASImageHotspotViewImpl_withASIWidget_(self, w)];
}

ASImageHotspotViewImpl_Hotspot *ASImageHotspotViewImpl_findHotspotWithADImageView_withFloat_withFloat_(ASImageHotspotViewImpl *self, ADImageView *imageView, float viewX, float viewY) {
  if (self->hotspots_ != nil) {
    ASImageHotspotViewImpl_ImageTransform *transform = ASImageHotspotViewImpl_fromImageViewWithADImageView_(self, imageView);
    if (transform != nil) {
      ADPointF *normalizedImagePoint = [transform viewToNormalizedImageWithFloat:viewX withFloat:viewY];
      for (ASImageHotspotViewImpl_Hotspot * __strong hotspot in nil_chk(self->hotspots_)) {
        if ([((ASImageHotspotViewImpl_Hotspot *) nil_chk(hotspot)) containsWithFloat:((ADPointF *) nil_chk(normalizedImagePoint))->x_ withFloat:normalizedImagePoint->y_]) {
          return hotspot;
        }
      }
    }
  }
  return nil;
}

void ASImageHotspotViewImpl_setOnHotspotClickWithASIWidget_withNSString_withId_(ASImageHotspotViewImpl *self, id<ASIWidget> w, NSString *strValue, id objValue) {
  NSString *type = JreStrcat("$$", [((id<ASIWidget>) nil_chk(w)) getId], @"OnTouch");
  [((ASEventBus *) nil_chk([((id<ASIFragment>) nil_chk([w getFragment])) getEventBus])) offWithNSString:type];
  [((ASEventBus *) nil_chk([((id<ASIFragment>) nil_chk([w getFragment])) getEventBus])) onWithNSString:type withASEventBusHandlerArray:[IOSObjectArray newArrayWithObjects:(id[]){ create_ASImageHotspotViewImpl_1_initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_(self, w, objValue, type) } count:1 type:ASEventBusHandler_class_()]];
}

void ASImageHotspotViewImpl_setHotspotOverlayDrawableWithASIWidget_withNSString_withId_withADView_(ASImageHotspotViewImpl *self, id<ASIWidget> w2, NSString *strValue, id objValue, ADView *view) {
  self->hotspotOverlayDrawable_ = (NSString *) cast_chk(objValue, [NSString class]);
}

void ASImageHotspotViewImpl_setHotspotOverlayDrawablesByTypeWithASIWidget_withNSString_withId_withADView_(ASImageHotspotViewImpl *self, id<ASIWidget> w2, NSString *strValue, id objValue, ADView *view) {
  self->hotspotOverlayDrawablesByType_ = ASModelExpressionParser_parseSimpleCssExpressionWithNSString_((NSString *) cast_chk(objValue, [NSString class]));
}

void ASImageHotspotViewImpl_setHotspotDetectOnlyOnceWithASIWidget_withNSString_withId_withADView_(ASImageHotspotViewImpl *self, id<ASIWidget> w2, NSString *strValue, id objValue, ADView *view) {
  self->hotspotDetectOnlyOnce_ = [((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue];
}

void ASImageHotspotViewImpl_addEventInfoWithJavaUtilMap_withASImageHotspotViewImpl_Hotspot_(id<JavaUtilMap> obj, ASImageHotspotViewImpl_Hotspot *hotspot) {
  ASImageHotspotViewImpl_initialize();
  id<JavaUtilMap> eventInfo = ASPluginInvoker_getJSONCompatMap();
  (void) [((id<JavaUtilMap>) nil_chk(eventInfo)) putWithId:@"id" withId:((ASImageHotspotViewImpl_Hotspot *) nil_chk(hotspot))->id__];
  (void) [eventInfo putWithId:@"type" withId:hotspot->type_];
  (void) [eventInfo putWithId:@"percX" withId:JavaLangFloat_valueOfWithFloat_(hotspot->percX_)];
  (void) [eventInfo putWithId:@"percY" withId:JavaLangFloat_valueOfWithFloat_(hotspot->percY_)];
  (void) [eventInfo putWithId:@"percWidth" withId:JavaLangFloat_valueOfWithFloat_(hotspot->percWidth_)];
  (void) [eventInfo putWithId:@"percHeight" withId:JavaLangFloat_valueOfWithFloat_(hotspot->percHeight_)];
  (void) [eventInfo putWithId:@"imageWidth" withId:JavaLangFloat_valueOfWithFloat_(hotspot->imageWidth_)];
  (void) [eventInfo putWithId:@"imageHeight" withId:JavaLangFloat_valueOfWithFloat_(hotspot->imageHeight_)];
  (void) [((id<JavaUtilMap>) nil_chk(obj)) putWithId:@"hotspot" withId:ASPluginInvoker_getNativeMapWithJavaUtilMap_(eventInfo)];
}

void ASImageHotspotViewImpl_addEventInfoWithJavaUtilMap_withJavaUtilMap_(id<JavaUtilMap> obj, id<JavaUtilMap> remainingHotSpotsByType) {
  ASImageHotspotViewImpl_initialize();
  id<JavaUtilMap> eventInfo = ASPluginInvoker_getJSONCompatMap();
  [((id<JavaUtilMap>) nil_chk(eventInfo)) putAllWithJavaUtilMap:remainingHotSpotsByType];
  (void) [((id<JavaUtilMap>) nil_chk(obj)) putWithId:@"remainingHotSpotsByType" withId:ASPluginInvoker_getNativeMapWithJavaUtilMap_(eventInfo)];
}

void ASImageHotspotViewImpl_showDebugHotspotsWithADImageView_(ASImageHotspotViewImpl *self, ADImageView *imageView) {
  if (self->hotspots_ == nil) {
    return;
  }
  [((ADViewOverlay *) nil_chk([((ADImageView *) nil_chk(imageView)) getOverlay])) clear];
  ASImageHotspotViewImpl_ImageTransform *transform = ASImageHotspotViewImpl_fromImageViewWithADImageView_(self, imageView);
  if (transform == nil) {
    return;
  }
  for (ASImageHotspotViewImpl_Hotspot * __strong hotspot in nil_chk(self->hotspots_)) {
    ADPointF *topLeft = [transform imageToViewWithFloat:((ASImageHotspotViewImpl_Hotspot *) nil_chk(hotspot))->percX_ withFloat:hotspot->percY_];
    ADPointF *bottomRight = [transform imageToViewWithFloat:hotspot->percX_ + hotspot->percWidth_ withFloat:hotspot->percY_ + hotspot->percHeight_];
    ADDrawable *debugDrawable = ASImageHotspotViewImpl_createDebugDrawableWithInt_withInt_withInt_withInt_(self, JavaLangMath_roundWithFloat_(((ADPointF *) nil_chk(topLeft))->x_), JavaLangMath_roundWithFloat_(topLeft->y_), JavaLangMath_roundWithFloat_(((ADPointF *) nil_chk(bottomRight))->x_), JavaLangMath_roundWithFloat_(bottomRight->y_));
    if (debugDrawable != nil) {
      [((ADViewOverlay *) nil_chk([imageView getOverlay])) addWithADDrawable:debugDrawable];
    }
  }
}

ADDrawable *ASImageHotspotViewImpl_createDebugDrawableWithInt_withInt_withInt_withInt_(ASImageHotspotViewImpl *self, int32_t left, int32_t top, int32_t right, int32_t bottom) {
  return nil;
}

ASImageHotspotViewImpl_ImageTransform *ASImageHotspotViewImpl_fromImageViewWithADImageView_(ASImageHotspotViewImpl *self, ADImageView *imageView) {
  ASRectM *bounds = [((ADImageView *) nil_chk(imageView)) getImageBoundsWithInt:[imageView getMeasuredWidth] withInt:[imageView getMeasuredHeight]];
  if (bounds == nil) {
    return nil;
  }
  ASImageHotspotViewImpl_ImageTransform *transform = new_ASImageHotspotViewImpl_ImageTransform_init();
  transform->scaleX_ = (float) bounds->width_ / [imageView getDrawableWidth];
  transform->scaleY_ = (float) bounds->height_ / [imageView getDrawableHeight];
  transform->translateX_ = bounds->x_;
  transform->translateY_ = bounds->y_;
  transform->imageWidth_ = [imageView getDrawableWidth];
  transform->imageHeight_ = [imageView getDrawableHeight];
  return transform;
}

void ASImageHotspotViewImpl_requestLayoutWithADImageView_(ASImageHotspotViewImpl *self, ADImageView *imageView) {
  [((ADImageView *) nil_chk(imageView)) requestLayout];
}

void ASImageHotspotViewImpl_setUseGcWithADDrawable_(ASImageHotspotViewImpl *self, ADDrawable *markerCopy) {
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASImageHotspotViewImpl)

J2OBJC_NAME_MAPPING(ASImageHotspotViewImpl, "com.ashera.imagehotspot", "AS")

@implementation ASImageHotspotViewImpl_Hotspot

- (instancetype)initWithASImageHotspotViewImpl:(ASImageHotspotViewImpl *)outer$ {
  ASImageHotspotViewImpl_Hotspot_initWithASImageHotspotViewImpl_(self, outer$);
  return self;
}

- (bool)containsWithFloat:(float)normalizedX
                withFloat:(float)normalizedY {
  float imageX = normalizedX * imageWidth_;
  float imageY = normalizedY * imageHeight_;
  float left = percX_ * imageWidth_;
  float top = percY_ * imageHeight_;
  float hotspotWidth = percWidth_ * imageWidth_;
  float hotspotHeight = percHeight_ * imageHeight_;
  return imageX >= left && imageX <= left + hotspotWidth && imageY >= top && imageY <= top + hotspotHeight;
}

- (NSString *)getType {
  return type_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASImageHotspotViewImpl:);
  methods[1].selector = @selector(containsWithFloat:withFloat:);
  methods[2].selector = @selector(getType);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "id__", "LNSString;", .constantValue.asLong = 0, 0x0, 3, -1, -1, -1 },
    { "type_", "LNSString;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "percX_", "F", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "found_", "Z", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "percY_", "F", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "percWidth_", "F", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "percHeight_", "F", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "imageWidth_", "F", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "imageHeight_", "F", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASImageHotspotViewImpl;", "contains", "FF", "id" };
  static const J2ObjcClassInfo _ASImageHotspotViewImpl_Hotspot = { "Hotspot", "com.ashera.imagehotspot", ptrTable, methods, fields, 7, 0x2, 3, 9, 0, -1, -1, -1, -1 };
  return &_ASImageHotspotViewImpl_Hotspot;
}

@end

void ASImageHotspotViewImpl_Hotspot_initWithASImageHotspotViewImpl_(ASImageHotspotViewImpl_Hotspot *self, ASImageHotspotViewImpl *outer$) {
  NSObject_init(self);
}

ASImageHotspotViewImpl_Hotspot *new_ASImageHotspotViewImpl_Hotspot_initWithASImageHotspotViewImpl_(ASImageHotspotViewImpl *outer$) {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl_Hotspot, initWithASImageHotspotViewImpl_, outer$)
}

ASImageHotspotViewImpl_Hotspot *create_ASImageHotspotViewImpl_Hotspot_initWithASImageHotspotViewImpl_(ASImageHotspotViewImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl_Hotspot, initWithASImageHotspotViewImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASImageHotspotViewImpl_Hotspot)

@implementation ASImageHotspotViewImpl_ImageTransform

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASImageHotspotViewImpl_ImageTransform_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ADPointF *)viewToNormalizedImageWithFloat:(float)x
                                   withFloat:(float)y {
  float imageX = (x - translateX_) / scaleX_;
  float imageY = (y - translateY_) / scaleY_;
  return new_ADPointF_initWithFloat_withFloat_(imageX / imageWidth_, imageY / imageHeight_);
}

- (ADPointF *)imageToViewWithFloat:(float)normalisedX
                         withFloat:(float)normalisedY {
  float x = normalisedX * imageWidth_;
  float y = normalisedY * imageHeight_;
  return new_ADPointF_initWithFloat_withFloat_(x * scaleX_ + translateX_, y * scaleY_ + translateY_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADPointF;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LADPointF;", 0x1, 2, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(viewToNormalizedImageWithFloat:withFloat:);
  methods[2].selector = @selector(imageToViewWithFloat:withFloat:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "scaleX_", "F", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "scaleY_", "F", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "translateX_", "F", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "translateY_", "F", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "imageWidth_", "I", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "imageHeight_", "I", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "viewToNormalizedImage", "FF", "imageToView", "LASImageHotspotViewImpl;" };
  static const J2ObjcClassInfo _ASImageHotspotViewImpl_ImageTransform = { "ImageTransform", "com.ashera.imagehotspot", ptrTable, methods, fields, 7, 0x9, 3, 6, 3, -1, -1, -1, -1 };
  return &_ASImageHotspotViewImpl_ImageTransform;
}

@end

void ASImageHotspotViewImpl_ImageTransform_init(ASImageHotspotViewImpl_ImageTransform *self) {
  NSObject_init(self);
}

ASImageHotspotViewImpl_ImageTransform *new_ASImageHotspotViewImpl_ImageTransform_init() {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl_ImageTransform, init)
}

ASImageHotspotViewImpl_ImageTransform *create_ASImageHotspotViewImpl_ImageTransform_init() {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl_ImageTransform, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASImageHotspotViewImpl_ImageTransform)

@implementation ASImageHotspotViewImpl_1

- (instancetype)initWithASImageHotspotViewImpl:(ASImageHotspotViewImpl *)outer$
                                 withASIWidget:(id<ASIWidget>)capture$0
                                        withId:(id)capture$1
                                  withNSString:(NSString *)type {
  ASImageHotspotViewImpl_1_initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_(self, outer$, capture$0, capture$1, type);
  return self;
}

- (void)doPerformWithId:(id)payload {
  id<JavaUtilMap> map = ASPluginInvoker_getMapWithId_([((id<JavaUtilMap>) nil_chk(ASPluginInvoker_getMapWithId_(payload))) getWithId:@"eventInfo"]);
  int32_t action = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([((id<JavaUtilMap>) nil_chk(map)) getWithId:@"action"], [JavaLangInteger class]))) intValue];
  if (action == ADMotionEvent_ACTION_UP) {
    int32_t x = [((NSNumber *) nil_chk(((NSNumber *) cast_chk([map getWithId:@"x"], [NSNumber class])))) intValue];
    int32_t y = [((NSNumber *) nil_chk(((NSNumber *) cast_chk([map getWithId:@"y"], [NSNumber class])))) intValue];
    ASImageHotspotViewImpl_Hotspot *hotspot = ASImageHotspotViewImpl_findHotspotWithADImageView_withFloat_withFloat_(this$0_, (ADImageView *) cast_chk([((id<ASIWidget>) nil_chk(val$w_)) asWidget], [ADImageView class]), x, y);
    if (hotspot != nil) {
      ASImageHotspotViewImpl_1_addOverlayWithASIWidget_withASImageHotspotViewImpl_Hotspot_(self, val$w_, hotspot);
      hotspot->found_ = true;
      ASImageHotspotViewImpl_OnHotspotClickListener *listener = new_ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_(val$w_, (NSString *) cast_chk(val$objValue_, [NSString class]));
      id<JavaUtilMap> remainingHotSpotsByType = ASImageHotspotViewImpl_1_getRemainingHotspotsByType(self);
      [listener onHotspotClickWithASImageHotspotViewImpl_Hotspot:hotspot withInt:(int32_t) [((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilList>) nil_chk(this$0_->hotspots_)) stream])) filterWithJavaUtilFunctionPredicate:JreLoadStatic(ASImageHotspotViewImpl_1_$Lambda$1, instance)])) count] withJavaUtilMap:remainingHotSpotsByType];
      if (this$0_->hotspotDetectOnlyOnce_) {
        [((id<JavaUtilList>) nil_chk(this$0_->hotspots_)) removeWithId:hotspot];
      }
    }
  }
}

- (id<JavaUtilMap>)getRemainingHotspotsByType {
  return ASImageHotspotViewImpl_1_getRemainingHotspotsByType(self);
}

- (void)addOverlayWithASIWidget:(id<ASIWidget>)w
withASImageHotspotViewImpl_Hotspot:(ASImageHotspotViewImpl_Hotspot *)hotspot {
  ASImageHotspotViewImpl_1_addOverlayWithASIWidget_withASImageHotspotViewImpl_Hotspot_(self, w, hotspot);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 1, 2, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x2, -1, -1, -1, 3, -1, -1 },
    { NULL, "V", 0x2, 4, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASImageHotspotViewImpl:withASIWidget:withId:withNSString:);
  methods[1].selector = @selector(doPerformWithId:);
  methods[2].selector = @selector(getRemainingHotspotsByType);
  methods[3].selector = @selector(addOverlayWithASIWidget:withASImageHotspotViewImpl_Hotspot:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASImageHotspotViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$w_", "LASIWidget;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$objValue_", "LNSObject;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASImageHotspotViewImpl;LASIWidget;LNSObject;LNSString;", "doPerform", "LNSObject;", "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "addOverlay", "LASIWidget;LASImageHotspotViewImpl_Hotspot;", "LASImageHotspotViewImpl;", "setOnHotspotClickWithASIWidget:withNSString:withId:" };
  static const J2ObjcClassInfo _ASImageHotspotViewImpl_1 = { "", "com.ashera.imagehotspot", ptrTable, methods, fields, 7, 0x8000, 4, 3, 6, -1, 7, -1, -1 };
  return &_ASImageHotspotViewImpl_1;
}

@end

void ASImageHotspotViewImpl_1_initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_(ASImageHotspotViewImpl_1 *self, ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0, id capture$1, NSString *type) {
  self->this$0_ = outer$;
  self->val$w_ = capture$0;
  self->val$objValue_ = capture$1;
  ASEventBusHandler_initWithNSString_(self, type);
}

ASImageHotspotViewImpl_1 *new_ASImageHotspotViewImpl_1_initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_(ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0, id capture$1, NSString *type) {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl_1, initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_, outer$, capture$0, capture$1, type)
}

ASImageHotspotViewImpl_1 *create_ASImageHotspotViewImpl_1_initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_(ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0, id capture$1, NSString *type) {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl_1, initWithASImageHotspotViewImpl_withASIWidget_withId_withNSString_, outer$, capture$0, capture$1, type)
}

id<JavaUtilMap> ASImageHotspotViewImpl_1_getRemainingHotspotsByType(ASImageHotspotViewImpl_1 *self) {
  id<JavaUtilMap> remainingHotSpotsByType = new_JavaUtilHashMap_init();
  for (ASImageHotspotViewImpl_Hotspot * __strong hotspot in nil_chk(self->this$0_->hotspots_)) {
    if (((ASImageHotspotViewImpl_Hotspot *) nil_chk(hotspot))->found_) {
      continue;
    }
    NSString *type = [hotspot getType];
    JavaLangInteger *count = [remainingHotSpotsByType getWithId:type];
    if (count == nil) {
      count = JavaLangInteger_valueOfWithInt_(0);
    }
    (void) [remainingHotSpotsByType putWithId:type withId:JavaLangInteger_valueOfWithInt_([count intValue] + 1)];
  }
  return remainingHotSpotsByType;
}

void ASImageHotspotViewImpl_1_addOverlayWithASIWidget_withASImageHotspotViewImpl_Hotspot_(ASImageHotspotViewImpl_1 *self, id<ASIWidget> w, ASImageHotspotViewImpl_Hotspot *hotspot) {
  if (!((ASImageHotspotViewImpl_Hotspot *) nil_chk(hotspot))->found_ && (self->this$0_->hotspotOverlayDrawable_ != nil || self->this$0_->hotspotOverlayDrawablesByType_ != nil)) {
    ADImageView *imageView = (ADImageView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADImageView class]);
    ASImageHotspotViewImpl_ImageTransform *transform = ASImageHotspotViewImpl_fromImageViewWithADImageView_(self->this$0_, imageView);
    ADPointF *topLeft = [((ASImageHotspotViewImpl_ImageTransform *) nil_chk(transform)) imageToViewWithFloat:hotspot->percX_ withFloat:hotspot->percY_];
    ADPointF *bottomRight = [transform imageToViewWithFloat:hotspot->percX_ + hotspot->percWidth_ withFloat:hotspot->percY_ + hotspot->percHeight_];
    NSString *overlayDrawable;
    if (self->this$0_->hotspotOverlayDrawablesByType_ != nil) {
      overlayDrawable = (NSString *) cast_chk([self->this$0_->hotspotOverlayDrawablesByType_ getWithId:hotspot->type_], [NSString class]);
    }
    else {
      overlayDrawable = self->this$0_->hotspotOverlayDrawable_;
    }
    if (overlayDrawable != nil) {
      ADDrawable *markerCopy = (ADDrawable *) cast_chk([w quickConvertWithId:overlayDrawable withNSString:@"drawable"], [ADDrawable class]);
      ASImageHotspotViewImpl_setUseGcWithADDrawable_(self->this$0_, markerCopy);
      if (markerCopy != nil) {
        [markerCopy setBoundsWithInt:JreFpToInt(((ADPointF *) nil_chk(topLeft))->x_) withInt:JreFpToInt(topLeft->y_) withInt:JreFpToInt(((ADPointF *) nil_chk(bottomRight))->x_) withInt:JreFpToInt(bottomRight->y_)];
        [((ADViewOverlay *) nil_chk([((ADImageView *) nil_chk(imageView)) getOverlay])) addWithADDrawable:markerCopy];
        ASImageHotspotViewImpl_requestLayoutWithADImageView_(self->this$0_, imageView);
      }
    }
  }
}

J2OBJC_INITIALIZED_DEFN(ASImageHotspotViewImpl_1_$Lambda$1)

@implementation ASImageHotspotViewImpl_1_$Lambda$1

- (bool)testWithId:(ASImageHotspotViewImpl_Hotspot *)f {
  return !((ASImageHotspotViewImpl_Hotspot *) nil_chk(f))->found_;
}

- (id<JavaUtilFunctionPredicate>)and__WithJavaUtilFunctionPredicate:(id<JavaUtilFunctionPredicate>)arg0 {
  return JavaUtilFunctionPredicate_and__WithJavaUtilFunctionPredicate_(self, arg0);
}

- (id<JavaUtilFunctionPredicate>)negate {
  return JavaUtilFunctionPredicate_negate(self);
}

- (id<JavaUtilFunctionPredicate>)or__WithJavaUtilFunctionPredicate:(id<JavaUtilFunctionPredicate>)arg0 {
  return JavaUtilFunctionPredicate_or__WithJavaUtilFunctionPredicate_(self, arg0);
}

+ (void)initialize {
  if (self == [ASImageHotspotViewImpl_1_$Lambda$1 class]) {
    ASImageHotspotViewImpl_1_$Lambda$1_instance = new_ASImageHotspotViewImpl_1_$Lambda$1_init();
    J2OBJC_SET_INITIALIZED(ASImageHotspotViewImpl_1_$Lambda$1)
  }
}

@end

void ASImageHotspotViewImpl_1_$Lambda$1_init(ASImageHotspotViewImpl_1_$Lambda$1 *self) {
  NSObject_init(self);
}

ASImageHotspotViewImpl_1_$Lambda$1 *new_ASImageHotspotViewImpl_1_$Lambda$1_init() {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl_1_$Lambda$1, init)
}

ASImageHotspotViewImpl_1_$Lambda$1 *create_ASImageHotspotViewImpl_1_$Lambda$1_init() {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl_1_$Lambda$1, init)
}

@implementation ASImageHotspotViewImpl_ImageHotspotView

+ (const J2ObjcClassInfo *)__metadata {
  static const void *ptrTable[] = { "LASImageHotspotViewImpl;", "LASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener;" };
  static const J2ObjcClassInfo _ASImageHotspotViewImpl_ImageHotspotView = { "ImageHotspotView", "com.ashera.imagehotspot", ptrTable, NULL, NULL, 7, 0x608, 0, 0, 0, 1, -1, -1, -1 };
  return &_ASImageHotspotViewImpl_ImageHotspotView;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ASImageHotspotViewImpl_ImageHotspotView)

@implementation ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "Z", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(onHotspotClickWithASImageHotspotViewImpl_Hotspot:withInt:withJavaUtilMap:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "onHotspotClick", "LASImageHotspotViewImpl_Hotspot;ILJavaUtilMap;", "LASImageHotspotViewImpl_ImageHotspotView;" };
  static const J2ObjcClassInfo _ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener = { "OnHotspotClickListener", "com.ashera.imagehotspot", ptrTable, methods, NULL, 7, 0x609, 1, 0, 2, -1, -1, -1, -1 };
  return &_ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener)

@implementation ASImageHotspotViewImpl_OnHotspotClickListener

- (NSString *)getAction {
  return action_;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue {
  ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_(self, w, strValue);
  return self;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue
                     withNSString:(NSString *)action {
  ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_withNSString_(self, w, strValue, action);
  return self;
}

- (bool)onHotspotClickWithASImageHotspotViewImpl_Hotspot:(ASImageHotspotViewImpl_Hotspot *)hotspot
                                                 withInt:(int32_t)remainingHotSpots
                                         withJavaUtilMap:(id<JavaUtilMap>)remainingHotSpotsByType {
  bool result = true;
  if (action_ == nil || [action_ isEqual:@"onHotspotClick"]) {
    [((id<ASIWidget>) nil_chk(w_)) syncModelFromUiToPojoWithNSString:@"onHotspotClick"];
    id<JavaUtilMap> obj = [self getOnHotspotClickEventObjWithASImageHotspotViewImpl_Hotspot:hotspot withInt:remainingHotSpots withJavaUtilMap:remainingHotSpotsByType];
    NSString *commandName = (NSString *) cast_chk([((id<JavaUtilMap>) nil_chk(obj)) getWithId:ASEventExpressionParser_KEY_COMMAND_NAME], [NSString class]);
    NSString *commandType = (NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_COMMAND_TYPE], [NSString class]);
    switch (JreIndexOfStr(commandType, (id[]){ @"+" }, 1)) {
      case 0:
      if (ASEventCommandFactory_hasCommandWithNSString_(commandName)) {
        id commandResult = [((id<ASEventCommand>) nil_chk(ASEventCommandFactory_getCommandWithNSString_(commandName))) executeCommandWithASIWidget:w_ withJavaUtilMap:obj withNSObjectArray:[IOSObjectArray newArrayWithObjects:(id[]){ hotspot, JavaLangInteger_valueOfWithInt_(remainingHotSpots), remainingHotSpotsByType } count:3 type:NSObject_class_()]];
        if (commandResult != nil) {
          result = [(JavaLangBoolean *) cast_chk(commandResult, [JavaLangBoolean class]) booleanValue];
        }
      }
      break;
      default:
      break;
    }
    if ([obj containsKeyWithId:@"refreshUiFromModel"]) {
      id widgets = [obj removeWithId:@"refreshUiFromModel"];
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, widgets, true);
    }
    if ([((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds] != nil) {
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, [((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds], true);
    }
    if (strValue_ != nil && ![strValue_ isEmpty] && ![((NSString *) nil_chk([((NSString *) nil_chk(strValue_)) java_trim])) java_hasPrefix:@"+"]) {
      id<ASIActivity> activity = [((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getRootActivity];
      if (activity != nil) {
        [activity sendEventMessageWithJavaUtilMap:obj];
      }
    }
  }
  return result;
}

- (id<JavaUtilMap>)getOnHotspotClickEventObjWithASImageHotspotViewImpl_Hotspot:(ASImageHotspotViewImpl_Hotspot *)hotspot
                                                                       withInt:(int32_t)remainingHotSpots
                                                               withJavaUtilMap:(id<JavaUtilMap>)remainingHotSpotsByType {
  id<JavaUtilMap> obj = ASPluginInvoker_getJSONCompatMap();
  (void) [((id<JavaUtilMap>) nil_chk(obj)) putWithId:@"action" withId:@"action"];
  (void) [obj putWithId:@"eventType" withId:@"hotspotclick"];
  (void) [obj putWithId:@"fragmentId" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getFragmentId]];
  (void) [obj putWithId:@"actionUrl" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getActionUrl]];
  (void) [obj putWithId:@"namespace" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getNamespace]];
  if ([((id<ASIWidget>) nil_chk(w_)) getComponentId] != nil) {
    (void) [obj putWithId:@"componentId" withId:[((id<ASIWidget>) nil_chk(w_)) getComponentId]];
  }
  ASPluginInvoker_putJSONSafeObjectIntoMapWithJavaUtilMap_withNSString_withId_(obj, @"id", [((id<ASIWidget>) nil_chk(w_)) getId]);
  ASImageHotspotViewImpl_addEventInfoWithJavaUtilMap_withASImageHotspotViewImpl_Hotspot_(obj, hotspot);
  ASPluginInvoker_putJSONSafeObjectIntoMapWithJavaUtilMap_withNSString_withId_(obj, @"remainingHotSpots", JavaLangInteger_valueOfWithInt_(remainingHotSpots));
  ASImageHotspotViewImpl_addEventInfoWithJavaUtilMap_withJavaUtilMap_(obj, remainingHotSpotsByType);
  (void) ASEventExpressionParser_parseEventExpressionWithNSString_withJavaUtilMap_(strValue_, obj);
  [((id<ASIWidget>) nil_chk(w_)) updateModelToEventMapWithJavaUtilMap:obj withNSString:@"onHotspotClick" withNSString:(NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_EVENT_ARGS], [NSString class])];
  return obj;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, 4, 3, -1, 5, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getAction);
  methods[1].selector = @selector(initWithASIWidget:withNSString:);
  methods[2].selector = @selector(initWithASIWidget:withNSString:withNSString:);
  methods[3].selector = @selector(onHotspotClickWithASImageHotspotViewImpl_Hotspot:withInt:withJavaUtilMap:);
  methods[4].selector = @selector(getOnHotspotClickEventObjWithASImageHotspotViewImpl_Hotspot:withInt:withJavaUtilMap:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "w_", "LASIWidget;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "view_", "LADView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "strValue_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "action_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASIWidget;LNSString;", "LASIWidget;LNSString;LNSString;", "onHotspotClick", "LASImageHotspotViewImpl_Hotspot;ILJavaUtilMap;", "getOnHotspotClickEventObj", "(Lcom/ashera/imagehotspot/ImageHotspotViewImpl$Hotspot;ILjava/util/Map;)Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;", "LASImageHotspotViewImpl;" };
  static const J2ObjcClassInfo _ASImageHotspotViewImpl_OnHotspotClickListener = { "OnHotspotClickListener", "com.ashera.imagehotspot", ptrTable, methods, fields, 7, 0xa, 5, 4, 6, -1, -1, -1, -1 };
  return &_ASImageHotspotViewImpl_OnHotspotClickListener;
}

@end

void ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_(ASImageHotspotViewImpl_OnHotspotClickListener *self, id<ASIWidget> w, NSString *strValue) {
  NSObject_init(self);
  self->w_ = w;
  self->strValue_ = strValue;
}

ASImageHotspotViewImpl_OnHotspotClickListener *new_ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl_OnHotspotClickListener, initWithASIWidget_withNSString_, w, strValue)
}

ASImageHotspotViewImpl_OnHotspotClickListener *create_ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl_OnHotspotClickListener, initWithASIWidget_withNSString_, w, strValue)
}

void ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_withNSString_(ASImageHotspotViewImpl_OnHotspotClickListener *self, id<ASIWidget> w, NSString *strValue, NSString *action) {
  NSObject_init(self);
  self->w_ = w;
  self->strValue_ = strValue;
  self->action_ = action;
}

ASImageHotspotViewImpl_OnHotspotClickListener *new_ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl_OnHotspotClickListener, initWithASIWidget_withNSString_withNSString_, w, strValue, action)
}

ASImageHotspotViewImpl_OnHotspotClickListener *create_ASImageHotspotViewImpl_OnHotspotClickListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl_OnHotspotClickListener, initWithASIWidget_withNSString_withNSString_, w, strValue, action)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASImageHotspotViewImpl_OnHotspotClickListener)

J2OBJC_INITIALIZED_DEFN(ASImageHotspotViewImpl_$Lambda$1)

@implementation ASImageHotspotViewImpl_$Lambda$1

- (id)applyWithId:(id<ASIWidget>)w {
  return new_ASImageHotspotViewImpl_initWithASIWidget_(w);
}

- (id<JavaUtilFunctionFunction>)composeWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_composeWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilFunctionFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

+ (void)initialize {
  if (self == [ASImageHotspotViewImpl_$Lambda$1 class]) {
    ASImageHotspotViewImpl_$Lambda$1_instance = new_ASImageHotspotViewImpl_$Lambda$1_init();
    J2OBJC_SET_INITIALIZED(ASImageHotspotViewImpl_$Lambda$1)
  }
}

@end

void ASImageHotspotViewImpl_$Lambda$1_init(ASImageHotspotViewImpl_$Lambda$1 *self) {
  NSObject_init(self);
}

ASImageHotspotViewImpl_$Lambda$1 *new_ASImageHotspotViewImpl_$Lambda$1_init() {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl_$Lambda$1, init)
}

ASImageHotspotViewImpl_$Lambda$1 *create_ASImageHotspotViewImpl_$Lambda$1_init() {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl_$Lambda$1, init)
}

@implementation ASImageHotspotViewImpl_$Lambda$2

- (void)run {
  ASImageHotspotViewImpl_showDebugHotspotsWithADImageView_(this$0_, (ADImageView *) cast_chk([((id<ASIWidget>) nil_chk(val$w_)) asWidget], [ADImageView class]));
}

@end

void ASImageHotspotViewImpl_$Lambda$2_initWithASImageHotspotViewImpl_withASIWidget_(ASImageHotspotViewImpl_$Lambda$2 *self, ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0) {
  self->this$0_ = outer$;
  self->val$w_ = capture$0;
  NSObject_init(self);
}

ASImageHotspotViewImpl_$Lambda$2 *new_ASImageHotspotViewImpl_$Lambda$2_initWithASImageHotspotViewImpl_withASIWidget_(ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0) {
  J2OBJC_NEW_IMPL(ASImageHotspotViewImpl_$Lambda$2, initWithASImageHotspotViewImpl_withASIWidget_, outer$, capture$0)
}

ASImageHotspotViewImpl_$Lambda$2 *create_ASImageHotspotViewImpl_$Lambda$2_initWithASImageHotspotViewImpl_withASIWidget_(ASImageHotspotViewImpl *outer$, id<ASIWidget> capture$0) {
  J2OBJC_CREATE_IMPL(ASImageHotspotViewImpl_$Lambda$2, initWithASImageHotspotViewImpl_withASIWidget_, outer$, capture$0)
}
