//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSImageHotspotPlugin\src\main\java\com\ashera\imagehotspot\ImageHotspotPlugin.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "EventCommandFactory.h"
#include "HotspotEventCommand.h"
#include "ImageHotspotPlugin.h"
#include "ImageHotspotViewImpl.h"
#include "J2ObjC_source.h"
#include "WidgetFactory.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation ASImageHotspotPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASImageHotspotPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASImageHotspotPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASImageHotspotPlugin = { "ImageHotspotPlugin", "com.ashera.imagehotspot", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASImageHotspotPlugin;
}

@end

void ASImageHotspotPlugin_init(ASImageHotspotPlugin *self) {
  NSObject_init(self);
}

ASImageHotspotPlugin *new_ASImageHotspotPlugin_init() {
  J2OBJC_NEW_IMPL(ASImageHotspotPlugin, init)
}

ASImageHotspotPlugin *create_ASImageHotspotPlugin_init() {
  J2OBJC_CREATE_IMPL(ASImageHotspotPlugin, init)
}

void ASImageHotspotPlugin_initPlugin() {
  ASImageHotspotPlugin_initialize();
  ASWidgetFactory_registerAttributableForWithNSString_withASIAttributable_(@"ImageView", new_ASImageHotspotViewImpl_init());
  ASEventCommandFactory_registerCommandWithNSString_withASEventCommand_(@"hotspot", new_ASHotspotEventCommand_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASImageHotspotPlugin)

J2OBJC_NAME_MAPPING(ASImageHotspotPlugin, "com.ashera.imagehotspot", "AS")
