//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSImageHotspotPlugin\src\main\java\com\ashera\imagehotspot\ImageHotspotViewImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ImageHotspotViewImpl")
#ifdef RESTRICT_ImageHotspotViewImpl
#define INCLUDE_ALL_ImageHotspotViewImpl 0
#else
#define INCLUDE_ALL_ImageHotspotViewImpl 1
#endif
#undef RESTRICT_ImageHotspotViewImpl

#if !defined (ASImageHotspotViewImpl_) && (INCLUDE_ALL_ImageHotspotViewImpl || defined(INCLUDE_ASImageHotspotViewImpl))
#define ASImageHotspotViewImpl_

#define RESTRICT_IAttributable 1
#define INCLUDE_ASIAttributable 1
#include "IAttributable.h"

@class ASImageHotspotViewImpl_Hotspot;
@class ASWidgetAttribute;
@class NSString;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASImageHotspotViewImpl : NSObject < ASIAttributable >

#pragma mark Public

- (instancetype)init;

+ (void)addEventInfoWithJavaUtilMap:(id<JavaUtilMap>)obj
 withASImageHotspotViewImpl_Hotspot:(ASImageHotspotViewImpl_Hotspot *)hotspot;

+ (void)addEventInfoWithJavaUtilMap:(id<JavaUtilMap>)obj
                    withJavaUtilMap:(id<JavaUtilMap>)remainingHotSpotsByType;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (NSString *)getLocalName;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIAttributable>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

@end

J2OBJC_EMPTY_STATIC_INIT(ASImageHotspotViewImpl)

inline NSString *ASImageHotspotViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASImageHotspotViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASImageHotspotViewImpl, LOCAL_NAME, NSString *)

FOUNDATION_EXPORT void ASImageHotspotViewImpl_init(ASImageHotspotViewImpl *self);

FOUNDATION_EXPORT ASImageHotspotViewImpl *new_ASImageHotspotViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASImageHotspotViewImpl *create_ASImageHotspotViewImpl_init(void);

FOUNDATION_EXPORT void ASImageHotspotViewImpl_addEventInfoWithJavaUtilMap_withASImageHotspotViewImpl_Hotspot_(id<JavaUtilMap> obj, ASImageHotspotViewImpl_Hotspot *hotspot);

FOUNDATION_EXPORT void ASImageHotspotViewImpl_addEventInfoWithJavaUtilMap_withJavaUtilMap_(id<JavaUtilMap> obj, id<JavaUtilMap> remainingHotSpotsByType);

J2OBJC_TYPE_LITERAL_HEADER(ASImageHotspotViewImpl)

@compatibility_alias ComAsheraImagehotspotImageHotspotViewImpl ASImageHotspotViewImpl;


#endif

#if !defined (ASImageHotspotViewImpl_ImageTransform_) && (INCLUDE_ALL_ImageHotspotViewImpl || defined(INCLUDE_ASImageHotspotViewImpl_ImageTransform))
#define ASImageHotspotViewImpl_ImageTransform_

@class ADPointF;
@class JavaLangFloat;
@class JavaLangInteger;

@interface ASImageHotspotViewImpl_ImageTransform : NSObject {
 @public
  float scaleX_;
  float scaleY_;
  float translateX_;
  float translateY_;
  int32_t imageWidth_;
  int32_t imageHeight_;
}

#pragma mark Public

- (instancetype)init;

- (ADPointF *)imageToViewWithFloat:(float)normalisedX
                         withFloat:(float)normalisedY;

- (ADPointF *)viewToNormalizedImageWithFloat:(float)x
                                   withFloat:(float)y;

@end

J2OBJC_EMPTY_STATIC_INIT(ASImageHotspotViewImpl_ImageTransform)

FOUNDATION_EXPORT void ASImageHotspotViewImpl_ImageTransform_init(ASImageHotspotViewImpl_ImageTransform *self);

FOUNDATION_EXPORT ASImageHotspotViewImpl_ImageTransform *new_ASImageHotspotViewImpl_ImageTransform_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASImageHotspotViewImpl_ImageTransform *create_ASImageHotspotViewImpl_ImageTransform_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASImageHotspotViewImpl_ImageTransform)


#endif

#if !defined (ASImageHotspotViewImpl_ImageHotspotView_) && (INCLUDE_ALL_ImageHotspotViewImpl || defined(INCLUDE_ASImageHotspotViewImpl_ImageHotspotView))
#define ASImageHotspotViewImpl_ImageHotspotView_

@protocol ASImageHotspotViewImpl_ImageHotspotView < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(ASImageHotspotViewImpl_ImageHotspotView)

J2OBJC_TYPE_LITERAL_HEADER(ASImageHotspotViewImpl_ImageHotspotView)


#endif

#if !defined (ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener_) && (INCLUDE_ALL_ImageHotspotViewImpl || defined(INCLUDE_ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener))
#define ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener_

@class ASImageHotspotViewImpl_Hotspot;
@class JavaLangBoolean;
@class JavaLangInteger;
@protocol JavaUtilMap;

@protocol ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener < JavaObject >

- (bool)onHotspotClickWithASImageHotspotViewImpl_Hotspot:(ASImageHotspotViewImpl_Hotspot *)hotspot
                                                 withInt:(int32_t)remainingHotSpots
                                         withJavaUtilMap:(id<JavaUtilMap>)remainingHotSpotsByType;

@end

J2OBJC_EMPTY_STATIC_INIT(ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener)

J2OBJC_TYPE_LITERAL_HEADER(ASImageHotspotViewImpl_ImageHotspotView_OnHotspotClickListener)


#endif

#pragma pop_macro("INCLUDE_ALL_ImageHotspotViewImpl")
