//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSImageHotspotPlugin\src\main\java\com\ashera\imagehotspot\ImageHotspotPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ImageHotspotPlugin")
#ifdef RESTRICT_ImageHotspotPlugin
#define INCLUDE_ALL_ImageHotspotPlugin 0
#else
#define INCLUDE_ALL_ImageHotspotPlugin 1
#endif
#undef RESTRICT_ImageHotspotPlugin

#if !defined (ASImageHotspotPlugin_) && (INCLUDE_ALL_ImageHotspotPlugin || defined(INCLUDE_ASImageHotspotPlugin))
#define ASImageHotspotPlugin_

@interface ASImageHotspotPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASImageHotspotPlugin)

FOUNDATION_EXPORT void ASImageHotspotPlugin_init(ASImageHotspotPlugin *self);

FOUNDATION_EXPORT ASImageHotspotPlugin *new_ASImageHotspotPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASImageHotspotPlugin *create_ASImageHotspotPlugin_init(void);

FOUNDATION_EXPORT void ASImageHotspotPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASImageHotspotPlugin)

@compatibility_alias ComAsheraImagehotspotImageHotspotPlugin ASImageHotspotPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_ImageHotspotPlugin")
